export const redirects: Record<string, string> = {
    '/': '/fi/',
    '/about-me/': '/en/about/',
    '/blogi/': '/fi/blog/',
    '/blogi/aanestin-lansiradan-puolesta/': '/fi/blog/46/aanestin-lansiradan-puolesta/',
    '/blogi/aluevaalit/': '/fi/category/aluevaalit/',
    '/blogi/aluevaalit2022/': '/fi/category/regional-elections-2022/',
    '/blogi/aluevaalit2025/': '/fi/category/regional-elections-2025/',
    '/blogi/digitalisaatio/': '/fi/category/digitalisation/',
    '/blogi/ehdolle-aluevaaleihin/': '/fi/blog/7/ehdolle-aluevaaleihin/',
    '/blogi/ehdoton-ei-toisen-asteen-lukukausimaksuille/': '/fi/blog/36/ehdoton-ei-toisen-asteen-lukukausimaksuille/',
    '/blogi/ennen-oli-paremmin/': '/fi/blog/13/ennen-oli-paremmin/',
    '/blogi/esseita-maahanmuutosta-maahanmuuton-maarasta/': '/fi/blog/24/esseita-maahanmuutosta-maahanmuuton-maarasta/',
    '/blogi/hyvin-suunniteltu-on-puoliksi-tehty-mutta/': '/fi/blog/5/hyvin-suunniteltu-on-puoliksi-tehty-mutta/',
    '/blogi/infra/': '/fi/category/infrastructure/',
    '/blogi/jokaisella-on-oikeus-olla-ylpea-olemassaolostaan/':
        '/fi/blog/40/jokaisella-on-oikeus-olla-ylpea-olemassaolostaan/',
    '/blogi/joukkoliikenne-ei-voi-kallistua-loputtomiin/': '/fi/blog/41/joukkoliikenne-ei-voi-kallistua-loputtomiin/',
    '/blogi/kasvava-kunta-tarvitsee-elinvoimaisen-keskustan/':
        '/fi/blog/35/kasvava-kunta-tarvitsee-elinvoimaisen-keskustan/',
    '/blogi/kirkkonummi/': '/fi/category/kirkkonummi/',
    '/blogi/kirkkonummi-lisa-on-sinunkin-etusi/': '/fi/blog/2/kirkkonummi-lisa-on-sinunkin-etusi/',
    '/blogi/kotihoidon-tuen-kuntalisa/': '/fi/blog/1/kotihoidon-tuen-kuntalisa/',
    '/blogi/koulutus-on-kunnan-tarkein-tehtava/': '/fi/blog/37/koulutus-on-kunnan-tarkein-tehtava/',
    '/blogi/koulutusko-erityissuojelussa/': '/fi/blog/27/koulutusko-erityissuojelussa/',
    '/blogi/kuka-paattaa-mista-puhumma/': '/fi/blog/43/kuka-paattaa-mista-puhumma/',
    '/blogi/kunnan-pitaa-suunnitella-pitkajanteisesti/': '/fi/blog/15/kunnan-pitaa-suunnitella-pitkajanteisesti/',
    '/blogi/kuntavaaleissa-ratkaistaan-arjen-asioita/': '/fi/blog/33/kuntavaaleissa-ratkaistaan-arjen-asioita/',
    '/blogi/kuntavaalit/': '/fi/category/kuntavaalit/',
    '/blogi/kuntavaalit-ja-aluevaalit-2025/': '/fi/blog/20/kuntavaalit-ja-aluevaalit-2025/',
    '/blogi/kuntavaalit2025/': '/fi/category/municipal-elections-2025/',
    '/blogi/kylma-riihi-kirkkonummelle/': '/fi/blog/38/kylma-riihi-kirkkonummelle/',
    '/blogi/lahiluontoa-pitaa-vaalia/': '/fi/blog/12/lahiluontoa-pitaa-vaalia/',
    '/blogi/lansi-uusimaa/': '/fi/category/western-uusimaa/',
    '/blogi/lansirata/': '/fi/category/west-railway/',
    '/blogi/lansirata-paatos-nosti-esiin-ongelmia-kirkkonummen-pitkajanteisessa-strategisessa-kehittamisessa/':
        '/fi/blog/50/lansirata-paatos-nosti-esiin-ongelmia-kirkkonummen-pitkajanteisessa-strategisessa-kehittamisessa/',
    '/blogi/lapsista-saastaminen-ei-kannata/': '/fi/blog/19/lapsista-saastaminen-ei-kannata/',
    '/blogi/liikenne/': '/fi/category/transportation/',
    '/blogi/luontomme-on-valttimme-vuodesta-toiseen/': '/fi/blog/17/luontomme-on-valttimme-vuodesta-toiseen/',
    '/blogi/luulo-ei-ole-tiedon-vaarti/': '/fi/blog/34/luulo-ei-ole-tiedon-vaarti/',
    '/blogi/maahanmuutto/': '/fi/category/immigration/',
    '/blogi/maahanmuuttokeskustelusta/': '/fi/blog/23/maahanmuuttokeskustelusta/',
    '/blogi/mita-jos-terveyskeskusta-ei-olisikaan/': '/fi/blog/9/mita-jos-terveyskeskusta-ei-olisikaan/',
    '/blogi/myytteja-maahanmuutosta/': '/fi/blog/42/myytteja-maahanmuutosta/',
    '/blogi/onnea-suomi/': '/fi/blog/25/onnea-suomi/',
    '/blogi/opetus/': '/fi/category/education/',
    '/blogi/osuuskauppavaalit/': '/fi/category/coop-elections/',
    '/blogi/osuuskauppavaalit-koskettavat-meita-kaikkia/': '/fi/blog/18/osuuskauppavaalit-koskettavat-meita-kaikkia/',
    '/blogi/paivakodit-kaipaavat-opettajia/': '/fi/blog/6/paivakodit-kaipaavat-opettajia/',
    '/blogi/passien-biometristen-tunnisteiden-kayttoa-ei-pida-laajentaa/':
        '/fi/blog/48/passien-biometristen-tunnisteiden-kayttoa-ei-pida-laajentaa/',
    '/blogi/perhesiteeseen-perustuvasta-maahanmuutosta/': '/fi/blog/26/perhesiteeseen-perustuvasta-maahanmuutosta/',
    '/blogi/perusoikeuksia-ei-pida-purkaa-perusteettomasti/':
        '/fi/blog/45/perusoikeuksia-ei-pida-purkaa-perusteettomasti/',
    '/blogi/perusturvajaosto-mika-se-on/': '/fi/blog/8/perusturvajaosto-mika-se-on/',
    '/blogi/puheilla-muovaamme-todellisuutta/': '/fi/blog/14/puheilla-muovaamme-todellisuutta/',
    '/blogi/sivistyksen-talo-lyyra-avaa-uusia-mahdollisuuksia-ja-nayttaa-suuntaa/':
        '/fi/blog/49/sivistyksen-talo-lyyra-avaa-uusia-mahdollisuuksia-ja-nayttaa-suuntaa/',
    '/blogi/sosiaalinen-media/': '/fi/category/social-media/',
    '/blogi/sote-on-hyvinvointiyhteiskunnan-kulmakivi/': '/fi/blog/10/sote-on-hyvinvointiyhteiskunnan-kulmakivi/',
    '/blogi/soteuudistus/': '/fi/category/health-and-social-reform/',
    '/blogi/tasa-arvo-ja-yhdenvertaisuus/': '/fi/category/equality-and-non-discrimination/',
    '/blogi/teknologia/': '/fi/category/technology/',
    '/blogi/tekoaly/': '/fi/category/artificial-intelligence/',
    '/blogi/tekoaly-ei-pysty-mihin-tahansa/': '/fi/blog/44/tekoaly-ei-pysty-mihin-tahansa/',
    '/blogi/terveys-kuuluu-kaikille/': '/fi/blog/11/terveys-kuuluu-kaikille/',
    '/blogi/turvapaikan-saaneista/': '/fi/blog/30/turvapaikan-saaneista/',
    '/blogi/turvapaikanhakijoista/': '/fi/blog/31/turvapaikanhakijoista/',
    '/blogi/tyoperaisesta-maahanmuutosta/': '/fi/blog/28/tyoperaisesta-maahanmuutosta/',
    '/blogi/ulkomailta-opiskelemaan-tulleista/': '/fi/blog/29/ulkomailta-opiskelemaan-tulleista/',
    '/blogi/uusi-vuosi-tuttu-talvikunnossapito/': '/fi/blog/16/uusi-vuosi-tuttu-talvikunnossapito/',
    '/blogi/valtuustoaloite/': '/fi/category/council-motion/',
    '/blogi/valtuustoaloite-vuosittainen-pride-liputus-kirkkonummelle/':
        '/fi/blog/39/valtuustoaloite-vuosittainen-pride-liputus-kirkkonummelle/',
    '/blogi/varhaiskasvatuksen-kerhotoiminta/': '/fi/blog/3/varhaiskasvatuksen-kerhotoiminta/',
    '/blogi/varhaiskasvatuksen-riittavyydesta-ei-saa-tinkia/':
        '/fi/blog/4/varhaiskasvatuksen-riittavyydesta-ei-saa-tinkia/',
    '/blogi/varhaiskasvatus/': '/fi/category/early-childhood-education/',
    '/blogi/vastuu-on-meidan-aikuisten/': '/fi/blog/21/vastuu-on-meidan-aikuisten/',
    '/blogi/vuosi-2026-on-tekoalyn/': '/fi/blog/47/vuosi-2026-on-tekoalyn/',
    '/blogi/yhdessa-olemme-vahvempia/': '/fi/blog/32/yhdessa-olemme-vahvempia/',
    '/blogi/yksi-askel-eteen-kaksi-taakse/': '/fi/blog/22/yksi-askel-eteen-kaksi-taakse/',
    '/blogi/yksityisyydensuoja/': '/fi/category/privacy/',
    // Issue #1077 — wrong-locale slug redirects (Google-indexed 404s)
    '/en/blog/16/uusi-vuosi-tuttu-talvikunnossapito/': '/en/blog/16/new-year-familiar-winter-maintenance/',
    '/en/blog/17/luontomme-on-valttimme-vuodesta-toiseen/': '/en/blog/17/our-nature-is-our-trump-card-year-after-year/',
    '/en/blog/46/aanestin-lansiradan-puolesta/': '/en/blog/46/i-voted-for-the-western-rail-link/',
    '/en/blog/48/passien-biometristen-tunnisteiden-kayttoa-ei-pida-laajentaa/':
        '/en/blog/48/the-use-of-biometric-identifiers-in-passports-must-not-be-expanded/',
    '/en/blog/52/kirkkonummi-on-tanaan-tasa-arvoisempi-kuin-eilen/':
        '/en/blog/52/kirkkonummi-is-more-equal-today-than-yesterday/',
    '/en/blog/56/lahteela-yhteinen-helmi-kirkkonummen-rannikolla/': '/en/blog/56/lahteela-a-gem-on-kirkkonummis-coast/',
    // Issue #1058 — English tag ID redirects (old Finnish category URLs → new English ones)
    '/en/category/aluevaalit2022/': '/en/category/regional-elections-2022/',
    '/en/category/aluevaalit2025/': '/en/category/regional-elections-2025/',
    '/en/category/digitaalinen-itsenaisyys/': '/en/category/digital-independence/',
    '/en/category/digitalisaatio/': '/en/category/digitalisation/',
    '/en/category/infra/': '/en/category/infrastructure/',
    '/en/category/kaavoitus/': '/en/category/urban-planning/',
    '/en/category/kuntavaalit2025/': '/en/category/municipal-elections-2025/',
    '/en/category/lansi-uusimaa/': '/en/category/western-uusimaa/',
    '/en/category/lansirata/': '/en/category/west-railway/',
    '/en/category/liikenne/': '/en/category/transportation/',
    '/en/category/maahanmuutto/': '/en/category/immigration/',
    '/en/category/opetus/': '/en/category/education/',
    '/en/category/osuuskauppavaalit/': '/en/category/coop-elections/',
    '/en/category/perusturva/': '/en/category/basic-welfare/',
    '/en/category/sivistys/': '/en/category/culture-and-education/',
    '/en/category/sosiaalinen-media/': '/en/category/social-media/',
    '/en/category/soteuudistus/': '/en/category/health-and-social-reform/',
    '/en/category/tasa-arvo-ja-yhdenvertaisuus/': '/en/category/equality-and-non-discrimination/',
    '/en/category/teknologia/': '/en/category/technology/',
    '/en/category/tekoaly/': '/en/category/artificial-intelligence/',
    '/en/category/valtuustoaloite/': '/en/category/council-motion/',
    '/en/category/varhaiskasvatus/': '/en/category/early-childhood-education/',
    '/en/category/yksityisyydensuoja/': '/en/category/privacy/',
    '/fi/blog/25/congratulations-finland/': '/fi/blog/25/onnea-suomi/',
    // Issue #1058 — Finnish category URL fixes
    '/fi/category/aluevaalit2022/': '/fi/category/regional-elections-2022/',
    '/fi/category/aluevaalit2025/': '/fi/category/regional-elections-2025/',
    '/fi/category/digitaalinen-itsenaisyys/': '/fi/category/digital-independence/',
    '/fi/category/digitalisaatio/': '/fi/category/digitalisation/',
    '/fi/category/infra/': '/fi/category/infrastructure/',
    '/fi/category/kaavoitus/': '/fi/category/urban-planning/',
    '/fi/category/kuntavaalit2025/': '/fi/category/municipal-elections-2025/',
    '/fi/category/lansi-uusimaa/': '/fi/category/western-uusimaa/',
    '/fi/category/lansirata/': '/fi/category/west-railway/',
    '/fi/category/liikenne/': '/fi/category/transportation/',
    '/fi/category/maahanmuutto/': '/fi/category/immigration/',
    '/fi/category/opetus/': '/fi/category/education/',
    '/fi/category/osuuskauppavaalit/': '/fi/category/coop-elections/',
    '/fi/category/perusturva/': '/fi/category/basic-welfare/',
    '/fi/category/sivistys/': '/fi/category/culture-and-education/',
    '/fi/category/sosiaalinen-media/': '/fi/category/social-media/',
    '/fi/category/soteuudistus/': '/fi/category/health-and-social-reform/',
    '/fi/category/tasa-arvo-ja-yhdenvertaisuus/': '/fi/category/equality-and-non-discrimination/',
    '/fi/category/teknologia/': '/fi/category/technology/',
    '/fi/category/tekoaly/': '/fi/category/artificial-intelligence/',
    '/fi/category/valtuustoaloite/': '/fi/category/council-motion/',
    '/fi/category/varhaiskasvatus/': '/fi/category/early-childhood-education/',
    '/fi/category/yksityisyydensuoja/': '/fi/category/privacy/',
    '/kategoria/aluevaalit2022/': '/fi/category/regional-elections-2022/',
    '/kategoria/aluevaalit2025/': '/fi/category/regional-elections-2025/',
    '/kategoria/digitaalinen-itsenaisyys/': '/fi/category/digital-independence/',
    '/kategoria/digitalisaatio/': '/fi/category/digitalisation/',
    '/kategoria/infra/': '/fi/category/infrastructure/',
    '/kategoria/kaavoitus/': '/fi/category/urban-planning/',
    '/kategoria/kirkkonummi/': '/fi/category/kirkkonummi/',
    '/kategoria/kuntavaalit2025/': '/fi/category/municipal-elections-2025/',
    '/kategoria/lansi-uusimaa/': '/fi/category/western-uusimaa/',
    '/kategoria/lansirata/': '/fi/category/west-railway/',
    '/kategoria/liikenne/': '/fi/category/transportation/',
    '/kategoria/maahanmuutto/': '/fi/category/immigration/',
    '/kategoria/opetus/': '/fi/category/education/',
    '/kategoria/osuuskauppavaalit/': '/fi/category/coop-elections/',
    '/kategoria/perusturva/': '/fi/category/basic-welfare/',
    '/kategoria/sivistys/': '/fi/category/culture-and-education/',
    '/kategoria/sosiaalinen-media/': '/fi/category/social-media/',
    '/kategoria/sosiaalinenMedia/': '/fi/category/social-media/',
    '/kategoria/soteuudistus/': '/fi/category/health-and-social-reform/',
    '/kategoria/tasa-arvo-ja-yhdenvertaisuus/': '/fi/category/equality-and-non-discrimination/',
    '/kategoria/teknologia/': '/fi/category/technology/',
    '/kategoria/tekoaly/': '/fi/category/artificial-intelligence/',
    '/kategoria/valtuustoaloite/': '/fi/category/council-motion/',
    '/kategoria/varhaiskasvatus/': '/fi/category/early-childhood-education/',
    '/kategoria/yksityisyydensuoja/': '/fi/category/privacy/',
    // Issue #1078 — top-level election campaign page redirects
    '/kommunalvalet-och-valfardsomradesvalet-2025/': '/sv/blog/20/kommun-och-valfardsvalet-2025/',
    '/kuntavaalit-ja-aluevaalit-2025/': '/fi/blog/20/kuntavaalit-ja-aluevaalit-2025/',
    '/minusta/': '/fi/about/',
    '/municipal-elections-and-county-elections-2025/': '/en/blog/20/municipal-and-regional-elections-2025/',
    '/om-mig/': '/sv/about/',
    '/ota-yhteytta/': '/fi/contact/',
    // Issue #1077 — wrong-locale slug redirects (Google-indexed 404s)
    '/sv/blog/14/puheilla-muovaamme-todellisuutta/': '/sv/blog/14/med-ord-formar-vi-verkligheten/',
    '/sv/blog/15/kunnan-pitaa-suunnitella-pitkajanteisesti/': '/sv/blog/15/kommunen-maste-planera-langsiktigt/',
    '/sv/blog/18/osuuskauppavaalit-koskettavat-meita-kaikkia/': '/sv/blog/18/vbo-valen-beror-oss-alla/',
    '/sv/blog/46/aanestin-lansiradan-puolesta/': '/sv/blog/46/jag-rostade-for-vasternabanan/',
    '/sv/blog/48/passien-biometristen-tunnisteiden-kayttoa-ei-pida-laajentaa/':
        '/sv/blog/48/anvandningen-av-biometriska-identifierare-i-pass-far-inte-utvidgas/',
    '/sv/blog/49/sivistyksen-talo-lyyra-avaa-uusia-mahdollisuuksia-ja-nayttaa-suuntaa/':
        '/sv/blog/49/lyyra-bildningens-hus-oppnar-nya-mojligheter-och-visar-vagen/',
    '/sv/blog/51/digitaalinen-itsenaisyys-on-valttamattomyys/':
        '/sv/blog/51/digital-sjalvstandighet-ar-en-nodvandighet/',
    '/sv/blog/52/kirkkonummi-on-tanaan-tasa-arvoisempi-kuin-eilen/':
        '/sv/blog/52/kyrsklatt-ar-mer-jamlikt-idag-an-det-var-igar/',
    '/sv/blog/56/lahteela-yhteinen-helmi-kirkkonummen-rannikolla/':
        '/sv/blog/56/lahteela-en-gemma-vid-kyrkslaendets-kust/',
    // Issue #1058 — Swedish category URL fixes
    '/sv/category/aluevaalit2022/': '/sv/category/regional-elections-2022/',
    '/sv/category/aluevaalit2025/': '/sv/category/regional-elections-2025/',
    '/sv/category/digitaalinen-itsenaisyys/': '/sv/category/digital-independence/',
    '/sv/category/digitalisaatio/': '/sv/category/digitalisation/',
    '/sv/category/infra/': '/sv/category/infrastructure/',
    '/sv/category/kaavoitus/': '/sv/category/urban-planning/',
    '/sv/category/kuntavaalit2025/': '/sv/category/municipal-elections-2025/',
    '/sv/category/lansi-uusimaa/': '/sv/category/western-uusimaa/',
    '/sv/category/lansirata/': '/sv/category/west-railway/',
    '/sv/category/liikenne/': '/sv/category/transportation/',
    '/sv/category/maahanmuutto/': '/sv/category/immigration/',
    '/sv/category/opetus/': '/sv/category/education/',
    '/sv/category/osuuskauppavaalit/': '/sv/category/coop-elections/',
    '/sv/category/perusturva/': '/sv/category/basic-welfare/',
    '/sv/category/sivistys/': '/sv/category/culture-and-education/',
    '/sv/category/sosiaalinen-media/': '/sv/category/social-media/',
    '/sv/category/soteuudistus/': '/sv/category/health-and-social-reform/',
    '/sv/category/tasa-arvo-ja-yhdenvertaisuus/': '/sv/category/equality-and-non-discrimination/',
    '/sv/category/teknologia/': '/sv/category/technology/',
    '/sv/category/tekoaly/': '/sv/category/artificial-intelligence/',
    '/sv/category/valtuustoaloite/': '/sv/category/council-motion/',
    '/sv/category/varhaiskasvatus/': '/sv/category/early-childhood-education/',
    '/sv/category/yksityisyydensuoja/': '/sv/category/privacy/',
}
