const config = {
    collectCoverageFrom: [
        '**/*.{js,jsx,ts,tsx}',
        '!**/*.spec.{js,jsx,ts,tsx}',
        '!**/*.mock.{js,jsx,ts,tsx}',
        '!**/node_modules/**',
        '!.cache/**',
        '!coverage/**',
        '!public/**',
        '!tests/e2e/**',
        '!src/types/**',
        '!.eslintrc.js',
        '!.prettierrc.js',
        '!env.ts',
        '!gatsby-browser.tsx',
        '!gatsby-config.ts',
        '!gatsby-node.js',
        '!gatsby-ssr.js',
        '!playwright.config.ts',
        '!knip.config.ts',
        '!tests/jest-preprocess.js',
        '!tests/jest.config.js',
        '!tests/snapshotResolver.js',
    ],
    coverageProvider: 'v8',
    globals: {
        __PATH_PREFIX__: ``,
    },
    moduleNameMapper: {
        '.+\\.(css|styl|less|sass|scss)$': `identity-obj-proxy`,
        '.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': `<rootDir>/tests/__mocks__/file-mock.js`,
    },
    rootDir: '..',
    setupFiles: [`<rootDir>/tests/loadershim.js`],
    setupFilesAfterEnv: ['<rootDir>/tests/setup-test-env.ts'],
    snapshotResolver: '<rootDir>/tests/snapshotResolver.js',
    testEnvironment: `jsdom`,
    testPathIgnorePatterns: [`node_modules`, `\\.cache`, `<rootDir>.*/public`, `tests/e2e`],
    transform: {
        '^.+\\.[jt]sx?$': `<rootDir>/tests/jest-preprocess.js`,
    },
    transformIgnorePatterns: [`node_modules/(?!(gatsby|gatsby-script|gatsby-link|gatsby-ssr)/)`],
}

module.exports = config
