name: pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build
        steps:
            - uses: actions/checkout@v3
            - uses: bahmutov/npm-install@v1.4.5
            - run: npm run build

    lint:
        runs-on: ubuntu-latest
        name: Lint
        steps:
            - uses: actions/checkout@v3
            - uses: bahmutov/npm-install@v1.4.5
            - run: npm run lint

    typecheck:
        runs-on: ubuntu-latest
        name: Typecheck
        steps:
            - uses: actions/checkout@v3
            - uses: bahmutov/npm-install@v1.4.5
            - run: npm run typecheck

    test-unit:
        runs-on: ubuntu-latest
        needs: [build, lint, typecheck]
        name: Unit tests
        if: ${{ github.event_name == 'push' }}
        steps:
            - uses: actions/checkout@v3
            - uses: bahmutov/npm-install@v1.4.5
            - run: npm test

    test-unit-report:
        runs-on: ubuntu-latest
        needs: [build, lint, typecheck]
        name: Unit tests with coverage report
        if: ${{ github.event_name == 'pull_request' }}
        steps:
            - uses: actions/checkout@v3
            - uses: bahmutov/npm-install@v1.4.5
            - uses: anuraag016/Jest-Coverage-Diff@master
              with:
                  runCommand: "npm run test -- --coverage --collectCoverage=true --coverageDirectory='./' --coverageReporters='json-summary'"

    test-e2e:
        runs-on: ubuntu-latest
        needs: [build, lint, typecheck]
        name: E2E tests
        steps:
            - uses: actions/checkout@v3
            - uses: bahmutov/npm-install@v1.4.5
            - run: npm run test:e2e
