name: Build and lint

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build_and_lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node: [16]

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install
              run: npm ci
            - name: Build
              run: npm run build
            - name: Lint
              run: npm run lint
            - name: Typecheck
              run: npm run typecheck
