name: pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build
        steps:
            - uses: actions/checkout@v3
            - uses: bahmutov/npm-install@v1.8.15
              with:
                  install-command: npm ci --force
            - run: npm run build

    lint:
        runs-on: ubuntu-latest
        name: Lint
        steps:
            - uses: actions/checkout@v3
            - uses: bahmutov/npm-install@v1.8.15
              with:
                  install-command: npm ci --force
            - run: npm run lint

    typecheck:
        runs-on: ubuntu-latest
        name: Typecheck
        steps:
            - uses: actions/checkout@v3
            - uses: bahmutov/npm-install@v1.8.15
              with:
                  install-command: npm ci --force
            - run: npm run typecheck

    test-unit:
        runs-on: ubuntu-latest
        needs: [build, lint, typecheck]
        name: Unit tests
        steps:
            - uses: actions/checkout@v3
            - uses: bahmutov/npm-install@v1.8.15
              with:
                  install-command: npm ci --force
            - run: npm test

    test-e2e:
        runs-on: ubuntu-latest
        needs: [build, lint, typecheck]
        name: E2E tests
        steps:
            - uses: actions/checkout@v3
            - uses: bahmutov/npm-install@v1.8.15
              with:
                  install-command: npm ci --force
            - run: npm run test:e2e
