name: pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build
        env:
            CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
            CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - run: npm run build

    lint:
        runs-on: ubuntu-latest
        name: Lint
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Lint code
              run: npm run lint

    typecheck:
        runs-on: ubuntu-latest
        name: Typecheck
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Check types
              run: npm run typecheck

    test-unit:
        runs-on: ubuntu-latest
        needs: [build, lint, typecheck]
        name: Unit tests
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Run unit tests
              run: npm test

    test-e2e:
        runs-on: ubuntu-latest
        needs: [build, lint, typecheck]
        name: E2E tests
        env:
            CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
            CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npm run test:e2e-dev
              timeout-minutes: 30
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
